version: '3.7'
services:
  mir-simulation:
    # MIR-100 robot simulation
    image: mir-simulation
    user: root
    entrypoint: /entrypoint.bash
    build:
      context: .
    environment: 
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./custom_mir_robot/:/opt/workspace/src/custom_mir_robot:rw
    command: ["roslaunch", "custom_mir_robot", "maze_world.launch"]
    privileged: true
    